language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- gem install compass
- npm install -g bower grunt-cli
- bower install
deploy:
  provider: heroku
  api_key:
    secure: bmq12lcgEeW4M579MRYWcR82IxM1CRfKCqnrWcejR5x+jyN6y/KybmIykYiSqcIkzAZiFYJKYln0T0TIxiLcmTNTMsPT3ES0XjcUwptdwkeB4XnJfwXfPSRDBrEj2Ude74kkY5+VwxMdNoBiW9P/ZJyvr6sQcLtAyBdhMy7Pyjc=
  app: qapi-frontend
  on:
    repo: secretBears/qapi-frontend
    branch: master